version: "3.3"
services:
  registry:
    image: softleader/registry:2
    ports:
      - 5001:5001
    volumes:
      - ./:/var/lib/registry
    restart: always
  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 5000:80
    restart: always
    environment:
      REGISTRY_URL: http://registry:5000
      DELETE_IMAGES: "true"
      REGISTRY_TITLE: changeit
