FROM azul/zulu-openjdk-alpine:8-jre
LABEL maintainer="softleader.com.tw"

RUN apk update &&\
    apk --no-cache add curl bash tzdata &&\
    rm -rf /var/cache/apk/* &&\
    cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime &&\
    echo "Asia/Taipei" > /etc/timezone &&\
    apk del tzdata

ENV SL_HOME /app
ENV SL_DUMPS /tmp/dumps
ENV SL_LOGS /tmp/logs
