FROM azul/zulu-openjdk-alpine:11-jre
LABEL maintainer="softleader.com.tw"

RUN apk update &&\
    apk --no-cache add curl bash tzdata &&\
    rm -rf /var/cache/apk/* &&\
    cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime &&\
    echo "Asia/Taipei" > /etc/timezone &&\
    apk del tzdata
