version: '3'

services:
  sftp-image:
    build: .
    environment:
      # HOST: softleader.com.tw
      # POST: 2224
      USER: transglobe
      PASSWORD: R7ygMGwD
      REMOTE_DIR: /TransGlobe
      # TAR_NAME: # 預設為: images-當前時間到秒.tar
    # command: # 可以在這邊指定 images, 或是在 docker compose run 時指定
    #   - alpine
    #   - busybox
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
