FROM node:24-bookworm-slim
LABEL maintainer="softleader.com.tw"

WORKDIR /app

ARG PNPM_VERSION=latest

ENV NODE_OPTIONS="--dns-result-order=ipv4first"

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends make zip; \
    npm install -g pnpm@"${PNPM_VERSION}"; \
    rm -rf /var/lib/apt/lists/*