FROM node:22.14-alpine
LABEL maintainer="softleader.com.tw"

WORKDIR /app

ARG PNPM_VERSION=latest

ENV NODE_OPTIONS="--dns-result-order=ipv4first"

RUN apk add --no-cache make npm zip && \
    npm install -g pnpm@${PNPM_VERSION} && \
    rm -rf /var/cache/apk/*