FROM tomcat:9.0-jdk8-corretto-al2
MAINTAINER softleader.com.tw

COPY ext-conf/server.xml /usr/local/tomcat/conf/server.xml
RUN yum -y update &&\
	  # 避免 upstream 有些 package 沒更新到被掃出風險, 這邊強制都 upgrade 一下
    yum -y upgrade &&\
    yum install -y curl bash tzdata fontconfig &&\
    yum clean all &&\
    cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime &&\
    echo "Asia/Taipei" > /etc/timezone

# runtime app home
ENV SL_HOME /tmp/app
ENV SL_DUMPS $SL_HOME
ENV SL_LOGS $SL_HOME
ENV TZ=Asia/Taipei

EXPOSE 8080
