FROM tomcat:9.0.84-jre8-temurin-jammy
MAINTAINER softleader.com.tw

RUN apk update &&\
	  # 避免 upstream 有些 package 沒更新到被掃出風險, 這邊強制都 upgrade 一下
	  apk --no-cache upgrade &&\
    apk --no-cache add curl bash tzdata &&\
    rm -rf /var/cache/apk/* &&\
    cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime &&\
    echo "Asia/Taipei" > /etc/timezone &&\
    apk del tzdata

# runtime app home
ENV SL_HOME /tmp/app
ENV SL_DUMPS $SL_HOME
ENV SL_LOGS $SL_HOME
ENV TZ=Asia/Taipei

EXPOSE 8080
