FROM tomcat:9.0.84-jre8-temurin-jammy
MAINTAINER softleader.com.tw

RUN apt update &&\
	  # 避免 upstream 有些 package 沒更新到被掃出風險, 這邊強制都 upgrade 一下
    apt -y upgrade &&\
    apt install -y curl bash tzdata &&\
    apt clean &&\
    cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime &&\
    echo "Asia/Taipei" > /etc/timezone

# runtime app home
ENV SL_HOME /tmp/app
ENV SL_DUMPS $SL_HOME
ENV SL_LOGS $SL_HOME
ENV TZ=Asia/Taipei

EXPOSE 8080
