#!/usr/bin/env bash

_pack=tmp
chart=""
values=""
args=("$@")
for i in "${!args[@]}"; do 
	if [ "$i" = "0" ]
	then
	    chart=${args[$i]}
	else
	    values="$values -f ${args[$i]}"
	fi
done

if [[ -z "$chart" ]]; then
  echo "chart is required";
  exit 1;
fi

# Merge different environments values into values.yaml
helm values $chart $values -o $chart || exit 1;

# Filter out files in templates-dir and copy to pack directory
helm filter $chart -o $_pack/$(dirname $chart) --overwrite-values || exit 1;

# Pack chart archive
helm package $_pack/$chart || exit 1;

# Remove pack directory 
echo "removing pack directory '$_pack'"
rm -rf $_pack || exit 1;

# Restore values.yaml from backup file
echo "Restoring '$chart/values.yaml' from backup file '$chart/values.yaml.bak '"
mv $chart/values.yaml.bak $chart/values.yaml || exit 1;

exit 0;
