name: azul-zulu-11

on:
  schedule:
    - cron: "30 15 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zulu-11-jre: # 這個是拿來比對的，讓我們的 harbor 掃描上層的 base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          buildkitd-config: .github/buildkitd.toml
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Tag and push
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: mirror.gcr.io/azul/zulu-openjdk-alpine:11-jre
          dst: harbor.softleader.com.tw/library/zulu-openjdk-alpine:11-jre
  zulu-11-jre-taipei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          buildkitd-config: .github/buildkitd.toml
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./azul-zulu/Dockerfile.11-jre-taipei
          tags: harbor.softleader.com.tw/library/zulu-openjdk-alpine:11-jre-taipei
          provenance: false
          no-cache: true
          pull: true
          push: true
  zulu-11-font-jre-taipei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          buildkitd-config: .github/buildkitd.toml
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./azul-zulu/Dockerfile.11-font-jre-taipei
          tags: harbor.softleader.com.tw/library/zulu-openjdk-alpine:11-font-jre-taipei
          provenance: false
          no-cache: true
          pull: true
          push: true

  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v5
      - uses: liskin/gh-workflow-keepalive@v1
