name: azul-zulu-8

on:
  schedule:
    - cron: "30 15 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zulu-8-jre: # 這個是拿來比對的, 讓我們的 harbor 掃描上層的 base image
    runs-on: [self-hosted, ubuntu-jammy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Tag and push
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/azul/zulu-openjdk-alpine:8-jre
          dst: harbor.softleader.com.tw/library/zulu-openjdk-alpine:8-jre
  azul-8-jre-taipei:
    runs-on: [self-hosted, ubuntu-jammy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./azul-zulu/Dockerfile.8-jre-taipei
          tags: harbor.softleader.com.tw/library/zulu-openjdk-alpine:8-jre-taipei
          provenance: false
          no-cache: true
          pull: true
          push: true
  zulu-8-font-jre-taipei:
    runs-on: [self-hosted, ubuntu-jammy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./azul-zulu/Dockerfile.8-font-jre-taipei
          tags: harbor.softleader.com.tw/library/zulu-openjdk-alpine:8-font-jre-taipei
          provenance: false
          no-cache: true
          pull: true
          push: true
