name: eclipse-temurin-21

on:
  schedule:
    - cron: "40 15 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  eclipse-temurin-21-jre: # 這個是拿來比對的，讓我們的 harbor 掃描上層的 base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          buildkitd-config: .github/buildkitd.toml
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Tag and push
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: mirror.gcr.io/eclipse-temurin:21-jre-alpine
          dst: harbor.softleader.com.tw/library/eclipse-temurin-alpine:21-jre
  eclipse-temurin-21-jre-taipei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          buildkitd-config: .github/buildkitd.toml
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./eclipse-temurin/Dockerfile.21-jre-taipei
          tags: harbor.softleader.com.tw/library/eclipse-temurin-alpine:21-jre-taipei
          provenance: false
          no-cache: true
          pull: true
          push: true
  eclipse-temurin-21-font-jre-taipei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          buildkitd-config: .github/buildkitd.toml
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./eclipse-temurin/Dockerfile.21-font-jre-taipei
          tags: harbor.softleader.com.tw/library/eclipse-temurin-alpine:21-font-jre-taipei
          provenance: false
          no-cache: true
          pull: true
          push: true

  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v6
      - uses: liskin/gh-workflow-keepalive@v1
