name: git

on:
  schedule:
    - cron: "00 16 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  _2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./git/Dockerfile.2
          tags: harbor.softleader.com.tw/library/git:2
          provenance: false
          no-cache: true
          pull: true
          push: true
