name: keep-actions-alive

on:
  schedule:
    - cron: "0 0 * * *"# In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/keepalive-workflow@v1
