name: Keep cronjob alive

on:
  schedule:
    - cron: "0 0 * * *"# In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      # This is how you use the ga-dree action
      - name: Inject dree
        uses: 'euberdeveloper/ga-dree@main'
        with:
          showMadeWithDree: 'false' # Does not add "Made with dree"
          exclude: .git/**,.github/**
      # In this step the changes to the branch are committed
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: inject dree (automated commit)"
          branch: master
      - uses: gautamkrishnar/keepalive-workflow@v1
