name: keep-actions-alive

on:
  schedule:
    - cron: "0 0 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: [self-hosted, ubuntu-jammy]
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
