name: maven-jdk17

on:
  schedule:
    - cron: "50 15 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  mavendaemon_3-eclipse-temurin-17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./mavendaemon/Dockerfile.3-eclipse-temurin-17
          tags: hharbor.softleader.com.tw/library/mvnd-jdk:3-eclipse-temurin-17
          provenance: false
          no-cache: true
          pull: true
          push: true

