name: nginx-unprivileged

on:
  schedule:
    - cron: "20 15 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stable-alpine: # 這個是拿來比對的, 讓我們的 harbor 掃描上層的 base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/Dockerfile
          tags: harbor.softleader.com.tw/library/nginx-unprivileged:stable-alpine
          no-cache: true
          pull: true
          push: true