name: tomcat9-temurin-8

on:
  schedule:
    - cron: "40 15 * * *" # In UTC time
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tomcat9-jre8-temurin-jammy: # 這個是拿來比對的, 讓我們的 harbor 掃描上層的 base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Tag and push
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/tomcat:9-jre8-temurin-jammy
          dst: harbor.softleader.com.tw/library/tomcat:9-jre8-temurin-jammy
  tomcat9-jre8-temurin-jammy-taipei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tomcat9/Dockerfile.8-jre-taipei
          tags: harbor.softleader.com.tw/library/tomcat:9-jre8-temurin-jammy-taipei
          provenance: false
          no-cache: true
          pull: true
          push: true
  tomcat9-jre8-temurin-jammy-taipei-font:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: harbor.softleader.com.tw
          username: ${{ secrets.SL_HARBOR_ROBOT }}
          password: ${{ secrets.SL_HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tomcat9/Dockerfile.8-jre-taipei-font
          tags: harbor.softleader.com.tw/library/tomcat:9-jre8-temurin-jammy-taipei-font
          provenance: false
          no-cache: true
          pull: true
          push: true
